export const FETCH_All_VEHICLES_START = 'FETCH_All_VEHICLES_START';
export const FETCH_All_VEHICLES_SUCCESS = 'FETCH_All_VEHICLES_SUCCESS';
export const FETCH_All_VEHICLES_FAIL = 'FETCH_All_VEHICLES_FAIL';
export const FETCH_VEHICLE_DETAIL_START = 'FETCH_VEHICLE_DETAIL_START';
export const FETCH_VEHICLE_DETAIL_SUCCESS = 'FETCH_VEHICLE_DETAIL_SUCCESS';
export const FETCH_VEHICLE_DETAIL_FAIL = 'FETCH_VEHICLE_DETAIL_FAIL';
export const DELETE_VEHICLE_DETAIL = 'DELETE_VEHICLE_DETAIL';